
// Test deletion

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6555271cafb19dacf1737aac

###

DELETE http://localhost:3001/api/persons/

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellasvuo",
    "number": "040-12345678"
}


